"""
Pydantic schema for the partial-spoof corpus-level aggregation summary.
"""
from typing import Dict

from pydantic import BaseModel, Field


class PartialSpoofCorpusSummary(BaseModel):
    """Marginal counts over the aggregated partial-spoof corpus.

    Mirrors the JSON payload written by
    ``PartialSpoofOrchestrator._emit_corpus_summary``, so a report
    generated by the lightweight aggregator is a drop-in replacement.

    Attributes:
        generated_at: ISO-8601 UTC timestamp of the aggregation run.
        samples_total: Total rows in corpus_samples.csv.
        spoofed_words_total: Total rows in corpus_spoofed_words.csv.
        per_attack_total: Sample count per attack system.
        per_partition_total: Sample count per partition (not_jittered,
            jittered).
        per_cell: Sample count per (attack, partition) cell.
        per_quality_flag: Sample count per quality_flag value.
        attack_weights_target: Configured target attack-assignment weights.
        attack_weights_actual: Observed attack share in the aggregated
            corpus, for comparison against the target weights.
    """

    generated_at: str = Field(..., description="ISO-8601 UTC timestamp.")
    samples_total: int = Field(..., description="Total corpus_samples.csv rows.")
    spoofed_words_total: int = Field(
        ..., description="Total corpus_spoofed_words.csv rows."
    )
    per_attack_total: Dict[str, int] = Field(
        default_factory=dict, description="Sample count per attack system."
    )
    per_partition_total: Dict[str, int] = Field(
        default_factory=dict, description="Sample count per partition."
    )
    per_cell: Dict[str, Dict[str, int]] = Field(
        default_factory=dict, description="Sample count per (attack, partition)."
    )
    per_quality_flag: Dict[str, int] = Field(
        default_factory=dict, description="Sample count per quality_flag value."
    )
    attack_weights_target: Dict[str, float] = Field(
        default_factory=dict, description="Configured target attack weights."
    )
    attack_weights_actual: Dict[str, float] = Field(
        default_factory=dict, description="Observed attack share in the corpus."
    )
