"""
Manifest entry schema for the partial spoof corpus composition plan.

The manifest is the single source of truth for which bonafide file is
generated by which attack system, under which partition (main / jitter),
and which tiers are eligible. Generated once during pre-flight, then
consumed by each per-attack pipeline run as its dispatch slice.
"""
from pathlib import Path
from typing import List, Optional

from pydantic import BaseModel, Field


class ManifestEntry(BaseModel):
    """Single row of the partial spoof dispatch manifest.

    One ManifestEntry maps exactly one bonafide audio file to exactly
    one attack system and one boundary-jitter partition, with
    pre-computed tier eligibility derived from the Parakeet TDT word
    count and the MIN_WORDS_W1/W2/W3 thresholds from settings.

    Attributes:
        speaker_id: HABLA v2 speaker identifier (e.g., 'arf_00295').
        sample_key: Unique sample identifier formed from speaker_id and
            the bonafide audio basename. Used as the primary key across
            all downstream steps and checkpoints.
        audio_path: Absolute path to the bonafide audio file. Supports
            .wav, .flac, .mp3 (HABLA v2 mxm_* speakers use .mp3).
        split: HABLA dataset split (train, val, or test).
        partition: 'not_jittered' for the half of the corpus without
            boundary jitter, 'jittered' for the boundary-jitter half.
            Disjoint per speaker.
        attack: Target attack system. One of 'fishgram', 'qwen',
            'omnivoice', 'openvoice', 'chatterbox', 'outetts'.
        planned_tiers: Tiers this file is eligible for. Subset of
            ['W1', 'W2', 'W3']. Files with fewer than MIN_WORDS_W1 words
            are excluded from the manifest entirely.
        word_count: Number of words in the Parakeet TDT transcription.
        bonafide_transcript: The transcribed text. Cached at manifest
            generation time so per-attack runs need not re-invoke
            Parakeet on the full corpus.
    """

    speaker_id: str = Field(
        ...,
        description="HABLA v2 speaker identifier",
    )
    sample_key: str = Field(
        ...,
        description="Unique per-file primary key used across all steps",
    )
    audio_path: Path = Field(
        ...,
        description="Absolute path to the bonafide audio file",
    )
    split: str = Field(
        ...,
        description="HABLA dataset split: train, val, or test",
    )
    partition: str = Field(
        ...,
        description="Corpus partition: 'not_jittered' or 'jittered'",
    )
    attack: str = Field(
        ...,
        description=(
            "Attack system: fishgram, qwen, omnivoice, openvoice, "
            "chatterbox, outetts"
        ),
    )
    planned_tiers: List[str] = Field(
        ...,
        description="Tier eligibility list, subset of ['W1', 'W2', 'W3']",
    )
    word_count: int = Field(
        ...,
        description="Word count from Parakeet TDT transcription",
    )
    bonafide_transcript: Optional[str] = Field(
        default=None,
        description="Cached Parakeet transcription text",
    )

    class Config:
        """Pydantic model configuration."""

        frozen = False
        arbitrary_types_allowed = True
